// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AcknowledgeAlarm():Promise<main.FullAppState>;

export function AddKeyword(arg1:string):Promise<main.FullAppState>;

export function AddRssSource(arg1:string,arg2:string):Promise<main.FullAppState>;

export function AddTelegramSource(arg1:string,arg2:string):Promise<main.FullAppState>;

export function ClearKeywords():Promise<main.FullAppState>;

export function ClearNewsHistory():Promise<main.FullAppState>;

export function CloseWindow():Promise<void>;

export function ExportNewsCSV():Promise<string>;

export function ExportNewsCsvDialog():Promise<string>;

export function ExportSettingsDialog():Promise<string>;

export function ExportSettingsJSON():Promise<string>;

export function FetchAvailablePairs():Promise<main.FullAppState>;

export function GetState():Promise<main.FullAppState>;

export function HideWindow():Promise<void>;

export function ImportNewsCSV(arg1:string):Promise<main.FullAppState>;

export function ImportNewsCsvDialog():Promise<main.FullAppState>;

export function ImportSettingsDialog():Promise<main.FullAppState>;

export function ImportSettingsJSON(arg1:string):Promise<main.FullAppState>;

export function MinimizeWindow():Promise<void>;

export function OpenExternalUrl(arg1:string):Promise<void>;

export function RefreshData():Promise<main.FullAppState>;

export function RemoveKeyword(arg1:string):Promise<main.FullAppState>;

export function RemoveSource(arg1:string):Promise<main.FullAppState>;

export function SaveCryptoPanicToken(arg1:string):Promise<main.FullAppState>;

export function SelectCoin(arg1:string):Promise<main.FullAppState>;

export function SelectNews(arg1:string):Promise<main.FullAppState>;

export function SendDesktopNotification(arg1:string,arg2:string):Promise<void>;

export function SetAlarmEnabled(arg1:boolean):Promise<main.FullAppState>;

export function SetAutostart(arg1:boolean):Promise<main.FullAppState>;

export function SetLanguage(arg1:string):Promise<main.FullAppState>;

export function SetMaxStoredNews(arg1:number):Promise<main.FullAppState>;

export function SetMaxVibrations(arg1:number):Promise<main.FullAppState>;

export function SetNightHours(arg1:string,arg2:string):Promise<main.FullAppState>;

export function SetNightModeEnabled(arg1:boolean):Promise<main.FullAppState>;

export function SetSourceFilter(arg1:string):Promise<main.FullAppState>;

export function SetUseInternalBrowser(arg1:boolean):Promise<main.FullAppState>;

export function ShowWindow():Promise<void>;

export function SwitchSettingsSubTab(arg1:string):Promise<main.FullAppState>;

export function SwitchTab(arg1:string):Promise<main.FullAppState>;

export function ToggleAlwaysOnTop():Promise<main.FullAppState>;

export function ToggleFavorite(arg1:string):Promise<main.FullAppState>;

export function ToggleObservedCoin(arg1:string):Promise<main.FullAppState>;

export function ToggleSource(arg1:string,arg2:boolean):Promise<main.FullAppState>;

export function ToggleWindowVisibility():Promise<void>;
