// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcknowledgeAlarm() {
  return window['go']['main']['App']['AcknowledgeAlarm']();
}

export function AddKeyword(arg1) {
  return window['go']['main']['App']['AddKeyword'](arg1);
}

export function AddRssSource(arg1, arg2) {
  return window['go']['main']['App']['AddRssSource'](arg1, arg2);
}

export function AddTelegramSource(arg1, arg2) {
  return window['go']['main']['App']['AddTelegramSource'](arg1, arg2);
}

export function AddXSource(arg1, arg2) {
  return window['go']['main']['App']['AddXSource'](arg1, arg2);
}

export function ClearKeywords() {
  return window['go']['main']['App']['ClearKeywords']();
}

export function ClearNewsHistory() {
  return window['go']['main']['App']['ClearNewsHistory']();
}

export function ClearSourceFilters() {
  return window['go']['main']['App']['ClearSourceFilters']();
}

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function ExportNewsCSV() {
  return window['go']['main']['App']['ExportNewsCSV']();
}

export function ExportNewsCsvDialog() {
  return window['go']['main']['App']['ExportNewsCsvDialog']();
}

export function ExportSettingsDialog() {
  return window['go']['main']['App']['ExportSettingsDialog']();
}

export function ExportSettingsJSON() {
  return window['go']['main']['App']['ExportSettingsJSON']();
}

export function FetchAvailablePairs() {
  return window['go']['main']['App']['FetchAvailablePairs']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetXSessionQR() {
  return window['go']['main']['App']['GetXSessionQR']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function ImportNewsCSV(arg1) {
  return window['go']['main']['App']['ImportNewsCSV'](arg1);
}

export function ImportNewsCsvDialog() {
  return window['go']['main']['App']['ImportNewsCsvDialog']();
}

export function ImportSettingsDialog() {
  return window['go']['main']['App']['ImportSettingsDialog']();
}

export function ImportSettingsJSON(arg1) {
  return window['go']['main']['App']['ImportSettingsJSON'](arg1);
}

export function LoginX() {
  return window['go']['main']['App']['LoginX']();
}

export function LogoutX() {
  return window['go']['main']['App']['LogoutX']();
}

export function MarkAllNewsAsSeen() {
  return window['go']['main']['App']['MarkAllNewsAsSeen']();
}

export function MarkNewsAsSeen(arg1) {
  return window['go']['main']['App']['MarkNewsAsSeen'](arg1);
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function OpenExternalUrl(arg1) {
  return window['go']['main']['App']['OpenExternalUrl'](arg1);
}

export function RefreshData() {
  return window['go']['main']['App']['RefreshData']();
}

export function RemoveKeyword(arg1) {
  return window['go']['main']['App']['RemoveKeyword'](arg1);
}

export function RemoveSource(arg1) {
  return window['go']['main']['App']['RemoveSource'](arg1);
}

export function SaveCryptoPanicToken(arg1) {
  return window['go']['main']['App']['SaveCryptoPanicToken'](arg1);
}

export function SaveXSession(arg1, arg2) {
  return window['go']['main']['App']['SaveXSession'](arg1, arg2);
}

export function SelectCoin(arg1) {
  return window['go']['main']['App']['SelectCoin'](arg1);
}

export function SelectNews(arg1) {
  return window['go']['main']['App']['SelectNews'](arg1);
}

export function SendDesktopNotification(arg1, arg2) {
  return window['go']['main']['App']['SendDesktopNotification'](arg1, arg2);
}

export function SetAlarmEnabled(arg1) {
  return window['go']['main']['App']['SetAlarmEnabled'](arg1);
}

export function SetAutostart(arg1) {
  return window['go']['main']['App']['SetAutostart'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetMaxStoredNews(arg1) {
  return window['go']['main']['App']['SetMaxStoredNews'](arg1);
}

export function SetMaxVibrations(arg1) {
  return window['go']['main']['App']['SetMaxVibrations'](arg1);
}

export function SetNightHours(arg1, arg2) {
  return window['go']['main']['App']['SetNightHours'](arg1, arg2);
}

export function SetNightModeEnabled(arg1) {
  return window['go']['main']['App']['SetNightModeEnabled'](arg1);
}

export function SetSourceFilter(arg1) {
  return window['go']['main']['App']['SetSourceFilter'](arg1);
}

export function SetSourceFilters(arg1) {
  return window['go']['main']['App']['SetSourceFilters'](arg1);
}

export function SetUseInternalBrowser(arg1) {
  return window['go']['main']['App']['SetUseInternalBrowser'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function SwitchSettingsSubTab(arg1) {
  return window['go']['main']['App']['SwitchSettingsSubTab'](arg1);
}

export function SwitchTab(arg1) {
  return window['go']['main']['App']['SwitchTab'](arg1);
}

export function ToggleAllSources(arg1, arg2) {
  return window['go']['main']['App']['ToggleAllSources'](arg1, arg2);
}

export function ToggleAlwaysOnTop() {
  return window['go']['main']['App']['ToggleAlwaysOnTop']();
}

export function ToggleFavorite(arg1) {
  return window['go']['main']['App']['ToggleFavorite'](arg1);
}

export function ToggleObservedCoin(arg1) {
  return window['go']['main']['App']['ToggleObservedCoin'](arg1);
}

export function ToggleSource(arg1, arg2) {
  return window['go']['main']['App']['ToggleSource'](arg1, arg2);
}

export function ToggleSourceFilter(arg1) {
  return window['go']['main']['App']['ToggleSourceFilter'](arg1);
}

export function ToggleWindowVisibility() {
  return window['go']['main']['App']['ToggleWindowVisibility']();
}
